name: Deploy para AWS EC2 (Simplificado)

on:
  # Acionar via push na branch "deploy" OU manualmente pelo botão
  push:
    branches:
      - deploy
  workflow_dispatch:  # Permite acionar manualmente pela UI do GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Testar a conexão SSH com a EC2
      - name: Testar conexão SSH com a EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conexão SSH bem-sucedida!"
            whoami  # Deve retornar "ubuntu"
            docker --version  # Verifica se o Docker está instalado

      # Passo 2: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 3: Build da imagem Docker
      - name: Build da Imagem Docker
        run: |
          docker build -t car-truck-api .
          # Salvar a imagem no caminho correto ($GITHUB_WORKSPACE)
          docker save car-truck-api -o $GITHUB_WORKSPACE/car-truck-api.tar

      # Passo 4: Transferir a imagem e atualizar o container na EC2
      - name: Acessar EC2 via SSH e atualizar container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Adicionar o host ao known_hosts
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            
            # Parar e remover o container antigo
            docker stop car-truck-container || true
            docker rm car-truck-container || true
            
            # Transferir a imagem para a EC2
            scp -i <(echo "${{ secrets.EC2_SSH_KEY }}") $GITHUB_WORKSPACE/car-truck-api.tar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
            
            # Carregar a imagem e rodar o container
            docker load -i /home/ubuntu/car-truck-api.tar
            docker run -d -p 80:80 --name car-truck-container car-truck-api