name: Deploy para AWS EC2

on:
  push:
    branches:
      - deploy  # Executa o deploy quando algo for enviado para a branch deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Etapa para realizar o checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Configuração do AWS CLI com as credenciais
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Ajuste para sua região

      # Login no Amazon ECR
      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 339712704449.dkr.ecr.us-east-2.amazonaws.com

      # Build e Push da Imagem Docker para o ECR
      - name: Build e Push da Imagem Docker
        run: |
          docker build -t meu-repositorio .
          docker tag meu-repositorio:latest 339712704449.dkr.ecr.us-east-2.amazonaws.com/meu-repositorio:latest
          docker push 339712704449.dkr.ecr.us-east-2.amazonaws.com/meu-repositorio:latest

      # Acessar EC2 via SSH e atualizar o container
      - name: Acessar EC2 via SSH e atualizar container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Atualizar a imagem do Docker
            docker pull 339712704449.dkr.ecr.us-east-2.amazonaws.com/meu-repositorio:latest
            
            # Parar e remover o container antigo, se existir
            docker stop meu-container || true
            docker rm meu-container || true

            # Rodar o novo container com as variáveis de ambiente para o DVC
            docker run -d -p 80:8000 --name meu-container \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_DEFAULT_REGION=us-east-2 \
              339712704449.dkr.ecr.us-east-2.amazonaws.com/meu-repositorio:latest
