name: Deploy para AWS EC2

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Testar conexão SSH
      - name: Testar conexão SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Conexão SSH bem-sucedida!"
            docker --version

      # Passo 2: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 3: Build da imagem Docker
      - name: Build e exportar imagem
        run: |
          docker build -t car-truck-api .
          docker save car-truck-api -o car-truck-api.tar
          ls -lh car-truck-api.tar  # Verificar tamanho do arquivo

      # Passo 4: Transferir e implantar
      - name: Implantar na EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Preparar ambiente
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            
            # Criar arquivo temporário com a chave
            echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key.pem
            chmod 600 /tmp/ssh_key.pem
            
            # Transferir arquivo usando SCP
            scp -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem \
              runner@github.com:$GITHUB_WORKSPACE/car-truck-api.tar \
              /home/ubuntu/car-truck-api.tar

            # Gerenciar container
            docker stop car-truck-container || true
            docker rm car-truck-container || true
            
            # Carregar e executar imagem
            docker load -i /home/ubuntu/car-truck-api.tar
            docker run -d -p 80:80 --name car-truck-container car-truck-api
            
            # Limpeza
            rm /tmp/ssh_key.pem
            echo "🚀 Implantação concluída com sucesso!"