name: Deploy para AWS EC2 (Simplificado)

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do código (OBRIGATÓRIO)
      - name: Checkout do código
        uses: actions/checkout@v4

      # Etapa 2: Build da imagem Docker
      - name: Build da Imagem Docker
        run: |
          docker build -t car-truck-api .
          docker save car-truck-api > car-truck-api.tar

      # Etapa 3: Transferir a imagem para a EC2 e rodar
      - name: Acessar EC2 via SSH e atualizar container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Adicionar host ao known_hosts
            ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            # Parar e remover o container antigo
            docker stop car-truck-container || true
            docker rm car-truck-container || true

            # Transferir a imagem
            scp -i ${{ secrets.EC2_SSH_KEY }} $GITHUB_WORKSPACE/car-truck-api.tar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

            # Carregar e rodar a imagem
            docker load -i /home/ubuntu/car-truck-api.tar
            docker run -d -p 80:80 --name car-truck-container car-truck-api