name: Deploy para AWS EC2 (Simplificado)

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Testar conexão SSH
      - name: Testar conexão SSH com a EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conexão SSH bem-sucedida!"
            docker --version

      # Passo 2: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 3: Build da imagem Docker
      - name: Build da Imagem Docker
        run: |
          docker build -t car-truck-api .
          docker save car-truck-api -o car-truck-api.tar

      # Passo 4: Transferir imagem e atualizar container
      - name: Implantar na EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          scp: |
            'car-truck-api.tar' :/home/ubuntu/
          script: |
            docker stop car-truck-container || true
            docker rm car-truck-container || true
            docker load -i /home/ubuntu/car-truck-api.tar
            docker run -d -p 80:80 --name car-truck-container car-truck-api